### ISSUE TITLE
Uncaught TypeError: Cannot read property 'editor' of undefined

### ISSUE THREAD

**Issue by rsrini7** [jasongilman/proto-repl-sayid#4]
I am using windows 10 atom and i am getting below error. The error occured when i click on trace current file.

TypeError: Cannot read property 'editor' of undefined
    at atom-workspace.<anonymous> (file:///C:/Users/RSrini/.atom/packages/proto-repl-sayid/lib/proto-repl-sayid.coffee:224:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\atom-environment.js:1181:28)
    at EventEmitter.outerCallback (C:\Users\RSrini\AppData\Local\atom\app-1.13.1\resources\app.asar\src\application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

**Comment by gmp26** [comment]
Same in OSX.

**Comment by nmoya** [comment]
Still happens

**Comment by nmoya** [comment]
I just realized that even using a full qualified namespace, such as `(proto-repl.saved-values/save 1)` you still need to add a require call `(require 'proto-repl.saved-values)`. This solved for me.

**Comment by avidprogrammerc** [comment]
Still happening in OSX as well
